app/models.py
#_*_coding:utf-8_*_
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Text, DateTime
from datetime import datetime

Base = declarative_base()

class Tag(Base):
    __tablename__ = 'tag'
    id = Column(Integer, primary_key=True)
    tag_name = Column(String(32))       #标签名

class Article(Base):
    __tablename__ = 'article'
    id = Column(Integer, primary_key=True)
    title = Column(Text)            #文章标题
    content = Column(Text)          #文章内容，markdowm文本
    tag = Column(Text)              #文章所属标签（可以有多个标签，用'；'间隔）
    post_time = Column(DateTime, default=datetime.now())    #上传时间


'''
数据库设计
-----------------
--article文章表
-----------------
id              //自增id
title           //文章标题
content         //文章内容，markdown文本
tag             //标签字符串，用';'间隔多个标签
post_time       //上传时间



-----------------
--tag标签表
-----------------
id              //自增id
tag_name        //标签名
'''

app/__init__.py
#_*_coding:utf-8_*_
from flask import Flask
from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from config import *

engine = create_engine(DevConfig.database_url, encoding='utf-8', echo=True) #连接数据库
Session = sessionmaker(bind=engine)
db_session = Session()

def creat_app():
    app = Flask(__name__)
    app.config.from_object(DevConfig)

    from .home import home
    from .blog import blog
    app.register_blueprint(home)
    app.register_blueprint(blog, url_prefix="/blog")
    return app

app/blog/__init__.py
#_*_coding:utf-8_*_
from flask import Blueprint

blog = Blueprint('blog',__name__)

from . import views

app/blog/views.py
#_*_coding:utf-8_*_
from flask import render_template, request
from sqlalchemy import desc

from . import blog
from .. import db_session
from ..models import Tag, Article

@blog.route('/', methods=['GET'])
def bloglist():
    tags = db_session.query(Tag).all()
    articles = db_session.query(Article.id, Article.title, Article.tag, Article.post_time).order_by(desc(Article.post_time))
    return render_template("bloglist.html", tags=tags, articles=articles)

@blog.route('/list_by_tag', methods=['POST'])
def list_by_tag():
    tag = request.json
    #print(tag)
    tag_name = tag['tag']
    if tag_name == "全部":
        articles = db_session.query(Article.id, Article.title, Article.tag, Article.post_time).order_by(desc(Article.post_time))
    else:
        articles = db_session.query(Article.id, Article.title, Article.tag, Article.post_time).filter(Article.tag.like('%' + tag_name + '%')).order_by(desc(Article.post_time))
    return render_template("list_by_tag.html", articles=articles, tag_name=tag_name)


@blog.route('/article_detail/<article_id>')
def article_detail(article_id):
    article = db_session.query(Article).filter(Article.id == article_id).first()
    return render_template("article.html", article=article)

app/home/__init__.py
#_*_coding:utf-8_*_
from flask import Blueprint

home = Blueprint('home',__name__)

from . import views

app/home/views.py
#_*_coding:utf-8_*_
from flask import render_template
from sqlalchemy import desc

from . import home
from .. import db_session
from ..models import Tag, Article

@home.route('/', methods=['GET'])
def index():
    tags = db_session.query(Tag).all()
    articles = db_session.query(Article).order_by(desc(Article.post_time))
    return render_template('index.html', tags=tags, articles=articles)

main.py
#_*_coding:utf-8_*_
from app import creat_app

app = creat_app()

if __name__ == "__main__":
    app.run()

app/templates/_header.html
<header class="masthead" style="background-image:url({{ url_for('static', filename='img/header-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <div class="site-heading">
                    <h1>UntilTheDay's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap4</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#">Welcome</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("home.index") }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("blog.bloglist") }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/article.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div id="article_title"><h2 class="post-title" style="margin-bottom: 40px">{{ article.title }}</h2></div>
            <div id="article_markdown">{{ article.content | safe }}</div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>hljs.initHighlightingOnLoad();</script>
<script>
$(document).ready(function () {
    $("#article_markdown").html(marked($("#article_markdown").html()));
    $('pre code').each(function (i, block) {
        hljs.highlightBlock(block);
    });
});
</script>
{% endblock %}

app/templates/base.html
{% block head %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>UntilTheDay's Blog</title>

<!-- CSS -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/clean-blog.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/rainbow.css') }}">
<!--END CSS-->

<!-- FONTS -->
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!--END FONTS-->
{% endblock %}

<!--NAV-->
{% block nav %}
{% include '_nav.html' %}
{% include '_header.html' %}
{% endblock %}
<!--END NAV-->

<!--BODY-->
{% block content %}

{% endblock %}
<!--END BODY-->

<!--FOOTER-->
{% block footer %}
<footer>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p class="copyright text-muted">Copyright &copy; Anonymous Website 2018</p>
        </div>
    </div>
</div>
</footer>
{% endblock %}
<!--END FOOTER-->

<!--JS-->
{% block scripts %}
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/clean-blog.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/marked.js') }}"></script>
<script src="{{ url_for('static', filename='js/highlight.pack.js') }}"></script>S
{% endblock %}
<!--END-->

app/templates/bloglist.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="row">
        <div class="col-md-8" style="text-align: right"><h6>按标签筛选:</h6></div>
        <div class="col-md-4" style="margin-bottom: 40px;">
            <select class='custom-select' id="taglist" onchange="change();">
                <option value="all">全部</option>
                {% for tag in tags %}
                    <option value="{{ tag.tag_name }}">{{ tag.tag_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h4>BlogList</h4><hr>
            <div id="article_list" style="margin-top: 30px">
                {% include "list_by_date.html" %}
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
function change() {
    var tag = $("#taglist").find("option:selected").text();
    var data = {"tag":tag};
    $.ajax({
        type: 'POST',
        url: "{{ url_for('blog.list_by_tag') }}",
        data: JSON.stringify(data),
        contentType: 'application/json; charset=UTF-8',
        dataType: 'html',
        success:function (data) {
            $("#article_list").html(data);
        },
        error:function (data) {
            alert("Failed");
        }
    });
}
</script>    
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="row">
        <!--最近几篇文章显示区域-->
        <div class="col-md-9">
            <div class="page-heading"><h1><span class="badge badge-success">Lastest</span></h1><hr></div>
            {% for article in articles %}
            <div class="post-preview">
                <a href="{{ url_for("blog.article_detail", article_id=article.id) }}">
                    <h5 class="post-title" style="font-size: x-large">
                        {{ article.title }}
                    </h5>
                </a>
                <p class="post-subtitle">
                    Tags:
                    {% for article_tag in article.tag.split(';') %}
                    <a><span class="badge badge-pill badge-info">{{ article_tag }}</span></a>
                    {% endfor %}
                </p>
                <p class="post-meta">
                    {{ "Post at " + article.post_time|string }}
                </p>
            </div>
            <hr>
            {% endfor %}
        </div>
        <!--右侧标签区域-->
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Tags</h5>
                    {% for tag in tags %}
                    <a><span class="badge badge-pill badge-info" style="margin-bottom: 20px">{{ tag.tag_name }}</span></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_by_date.html
{% for article in articles %}
    <div class="post-preview">
        <a class="post-meta" href="{{ url_for("blog.article_detail", article_id=article.id) }}">
            <p>{{ article.post_time.date()|string + "   "  + article.title }}</p>
        </a>
        <div class="row">
        &nbsp;&nbsp;&nbsp;
        {% for tag in article.tag.split(';') %}
            <h6><span class="badge badge-pill badge-info">{{ tag }}</span></h6>&nbsp;
        {% endfor %}
        </div>
    </div>
{% endfor %}

app/templates/list_by_tag.html
<div style="margin-bottom: 40px">
    {% if tag_name != "全部" %}
    <h4><span class="badge badge-pill badge-dark">{{ tag_name }}</span></h4><hr>
    {% endif %}
    {% for article in articles %}
        <div class="post-preview">
            <a class="post-meta" href="{{ url_for("blog.article_detail", article_id=article.id) }}">
                <p>{{ article.post_time.date()|string + "   "  + article.title }}</p>
            </a>
        </div>
        <div class="row">
        &nbsp;&nbsp;&nbsp;
        {% for tag in article.tag.split(';') %}
            <h6><span class="badge badge-pill badge-info">{{ tag }}</span></h6>&nbsp;
        {% endfor %}
        </div>
    {% endfor %}
</div>